### ISSUE TITLE
MVKsentry - Improper handling of price normalization to `e18` in `RedstoneOracle.sol#getValueInEth`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#103] opened 2024-08-24 15:39 UTC
MVKsentry

High

# Improper handling of price normalization to `e18` in `RedstoneOracle.sol#getValueInEth`

### Summary

The RedstoneOracle#getValueInEth returns price of `ASSSETe18` mutiplied by `(ASSET/USD) / (ETH/USD)`which are gotten from Redstone Oracles and not scaled to 18 decimals as the `ASSET`.

The problem is that Redstone Oracles are 8 decimals by default which can be seen here [Redstone price feeds decimals](https://github.com/redstone-finance/redstone-oracles-monorepo/blob/9d10a48aad7a2ccb5f3f48396d970fd63761dbce/packages/on-chain-relayer/contracts/price-feeds/PriceFeedBase.sol#L51-L53)

### Root Cause

The issue itself lies in the normalization to `e18` of the returned by the method price.

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/RedstoneOracle.sol#L67-L71

### Impact

Financial losses due to inaccuracy in the math.

### PoC

As per openzeppelin math [mulDiv function parameters](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/0b58a783b9b33b63eef2994af8958c0c6a72dc51/contracts/utils/math/Math.sol#L144)
x = amt: Scaled to 18 decimals.
y = assetUsdPrice: 8 decimals.
denominator = ethUsdPrice: 8 decimals.

The calculation performed by the `getValueInEth` function is:
```math

\text{Result} = \frac{\text{amt} \times \text{assetUsdPrice}}{\text{ethUsdPrice}}
```

Substituting the values:
```math
\text{Result} = \frac{(1 \times 10^{18}) \times (1 \times 10^{8})}{2 \times 10^{8}}
```

Simplifying the expression:
```math
\text{Result} = \frac{1 \times 10^{26}}{2 \times 10^{8}} = \frac{1 \times 10^{26}}{2 \times 10^{8}} = 0.5 \times 10^{18} = 5 \times 10^{17}
```
Thus, the function will return:
```math
`\boxed{5 \times 10^{17}}
```

### Mitigation

Consider normalizing the prices of `assetUsdPrice, ethUsdPrice` to `1e18` OR the `asset` price to `1e8` and after that the calculation outcome value to `1e18`

**Comment by samuraii77** [comment] 2024-09-16 06:39
The example given works completely as intended. The user has provided 1 asset of some asset which was then normalized to 18 decimals, that asset is worth 1$ while ETH is worth 2$. Thus, the user has half an ETH which is what the function returns - 5e17.

**Comment by zarkk01** [comment] 2024-09-16 07:57
Escalate

For above comment.

**Comment by sherlock-admin3** [comment] 2024-09-16 07:57
> Escalate
> 
> For above comment.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Anirruth** [comment] 2024-09-16 08:02
The duplicate is a different issue.

**Comment by Anirruth** [comment] 2024-09-17 13:02
When checking this issue, do check the duplicate : [604](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/604) as its a different issue.

**Comment by MarioBozhikov** [comment] 2024-09-17 20:14
@samuraii77, in the case of an asset worth $1 and ETH worth $2, your math checks out, especially for small amounts. However, when dealing with larger amounts of assets or assets with low prices, the function can return inflated or deflated values due to the mismatch between the 18-decimal asset and 8-decimal price feeds. This discrepancy causes the result to be inaccurate, especially when scaling to larger or smaller values.

**Comment by MarioBozhikov** [comment] 2024-09-17 20:33
@Anirruth Both issues are caused by the mismatch between the 8-decimal price feeds from Redstone Oracles and the 18-decimal arithmetic used in the contract.

**Comment by Anirruth** [comment] 2024-09-18 04:48
In this issue its given that assetusdPrice and ethusdPrice are with 8 decimal precision, but my submission shows there are some standard erc20 tokens which returns with 1e18 decimal precision in different chains, which the code doesn't take into consideration. So in some instance the ethusdPrice will be in 8 decimal precision while the assetusdPrice will be in 18 decimal precision which will increase the amount by 10 times.

**Comment by ruvaag** [comment] 2024-09-27 12:15
this should be invalid imo.

it is not an issue if both assetUsdPrice and ethUsdPrice are 8 decimals since they cancel out without loss of precision. there might be something to be said about non-standard redstone feeds that don't have 8 decimals, but that is not part of the discussion here either.

**Comment by Anirruth** [comment] 2024-09-27 12:21
the dup of this issue [604](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/604) states a different issue, not related to this. The dup states the precision difference on different chains.

**Comment by cvetanovv** [comment] 2024-09-28 10:54
I agree with the sponsor's comment that we have no problem here. #604 is also invalid. 

If #103 and #604 try to write a real PoC(which is mandatory for this type of issue), they will see that we have no issue.

Planning to accept the escalation and invalidate the issue.

**Comment by Anirruth** [comment] 2024-09-28 11:07
> I agree with the sponsor's comment that we have no problem here. #604 is also invalid.
> 
> If #103 and #604 try to write a real PoC(which is mandatory for this type of issue), they will see that we have no issue.
> 
> Planning to accept the escalation and invalidate the issue.

Could you explain why 604 is invalid, since it shows that erc20 standard following tokens might have different precision (such as 1e18 as linked in the report) for chainlink price feeds in different chains while ethusd price is always in 1e8 precision, which causes the calculation to be 10 times higher since it divides `assetUsdPrice(1e18)` / `ethUsdPrice(1e8)`  and doesn't take the precision difference into consideration . Whereas 103 is not related to 604 at all and doesn't mention anything about chainlink precision difference in different chain at all.

**Comment by Anirruth** [comment] 2024-09-28 11:18
The etherscan address linked is from this - https://data.chain.link/feeds/arbitrum/mainnet/pepe-usd . If you click on the contract address and check the decimals in the read contract section on etherscan it shows 18. The contest details states that :
> On what chains are the smart contracts going to be deployed?

> Any EVM-compatbile network

But it doesn't take into account the precision difference in different chains. The token's chainlink oracle price in arbitrum is in 1e18 precision while in other chains it's in 1e8. The contract doesn't check the precision difference and always divides with the ethusd price which is in 1e8 precision. 
This is shown in issue 604. Hence why issue 604 should be valid.

**Comment by Anirruth** [comment] 2024-10-03 14:38
Could you check the messages sent by me which proves the validity of [604](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/604) , since it's not related to 103.  @cvetanovv @ruvaag

**Comment by cvetanovv** [comment] 2024-10-07 10:13
I don't see the problem in #604.

On line 82, you can see that decimals are taken on each asset:

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/ChainlinkUsdOracle.sol#L82

```solidity
uint256 decimals = IERC20Metadata(asset).decimals();
```

The function works correctly.

My decision to accept the escalation and invalidate the issue remains.

**Comment by Anirruth** [comment] 2024-10-07 10:33
Could you show where the line you linked changes the assetusdprice? The line you linked gets the decimals to make the amt to 18 decimal precision and has no influence over the assetusdprice. If you check the previous messages I've sent you will see that some tokens might return 18 decimals precision while ethusdprice is always 8 decimal precision. 
Edit : The line you linked doesn't change assetusdprice, only gets the amt to 18 decimals precision. So for example if the price of the asset returns 10e18 while eth price returns as 1000e8 the it will return price 10 times higher while dividing asset price / eth price in some chains, while the price of asset is supposed to return as 10e8. You can check the previous messages to see that the assst returns 18 decimal precision in arbitrum while 8 decimal precision in the other chains. @cvetanovv @ruvaag 
I think you misunderstood the issue since ,I've shown that some assets might return different precision oracle price which the code doesn't take into consideration.

**Comment by Anirruth** [comment] 2024-10-07 10:44
If you see the lines below the one you linked, you will see that the returned decimals doesn't change the assetusdprice. Do understand that the issue is that in some chains the assetusdprice might returns in 18 decimal precision while ethusdprice is always in 8 decimal precision which the code doesn't take into consideration and cause the price to be 10 times higher.

**Comment by Anirruth** [comment] 2024-10-07 10:47
@WangSecurity

**Comment by cvetanovv** [comment] 2024-10-08 16:54
`assetUsdPrice` can be set by the admin. And the admin is trusted to do it properly.

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/oracle/ChainlinkUsdOracle.sol#L89-L99

```solidity
    /// @notice Set Chainlink ETH-denominated feed for an asset
    /// @param asset Address of asset to be priced
    /// @param feed Address of the asset/eth chainlink feed
    /// @param stalePriceThreshold prices older than this duration are considered invalid, denominated in seconds
    /// @dev stalePriceThreshold must be equal or greater to the feed's heartbeat
    function setFeed(address asset, address feed, uint256 stalePriceThreshold) external onlyOwner {
        assert(IAggegregatorV3(feed).decimals() == 8);
        priceFeedFor[asset] = feed;
        stalePriceThresholdFor[feed] = stalePriceThreshold;
        emit FeedSet(asset, feed);
    }
 ```

Escalation will be rejected.

**Comment by WangSecurity** [comment] 2024-10-09 15:41
Result:
Medium
Has duplicates

**Comment by sherlock-admin4** [comment] 2024-10-09 15:41
Escalations have been resolved successfully!

Escalation status:
- [zarkk01](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/103/#issuecomment-2352241045): rejected

**Comment by Anirruth** [comment] 2024-10-09 17:14
I think the escalation should be accepted, since the judge gave reasons why the issues are invalid and maybe miswrote above for the escalation to be rejected. @WangSecurity

**Comment by zarkk01** [comment] 2024-10-09 17:19
@cvetanovv @WangSecurity Miswrote the rejection of the escalation while for the whole conversation it says that he is planning to accept it. Please, correct it. Thanks.

**Comment by cvetanovv** [comment] 2024-10-09 17:32
@Anirruth @zarkk01 Thanks for the correction. We'll accept the escalation.

**Comment by WangSecurity** [comment] 2024-10-09 20:24
@Anirruth @zarkk01 Yes, excuse me for a mistake here, the issue is invalidated. About accepting the escalation, it's hard to do that when the escalation is already rejected. So, I hope there's nothing wrong with you if we leave it rejected since, with the new Judging system, the escalation threshold is deprecated.

**Closed** 2024-10-09 20:24 UTC
Labels: Has Duplicates, Sponsor Disputed, Won't Fix, Escalation Resolved, Non-Reward
